#page title
page_title                                : Pkmn Yellow Token                                      # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.

app_icon                                  : # assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : Pkmn Yellow Token                    # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : The original 150 on the BSC!

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : PkmnYellowDevTeam                          
your_link                                 : https://pkmnyellow.com/                     
your_city                                 : New York                                
email_address                             : PkmnYellowDevTeam@gmail.com
telegram_username                         : PkmnYellowToken                       
instagram_username                        : 
twitter_username                          : PkmnYellowToken
github_username                           : 
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Catch em' on the BSC!
    description                           : Only 150 tokens are out there!
    fontawesome_icon_name                 : star
    
  - title                                 : Supportive Community!
    description                           : Join a respectful crypto community and learn about the world of cryptocurrencies!
    fontawesome_icon_name                 : star

  - title                                 : Exchange your Pkmn Yellow Tokens for NFTs!
    description                           : NFTs for each of the original 150 are in the works!
    fontawesome_icon_name                 : star
  
  - title                                 : Daycare Staking!
    description                           : Deposit your Pkmn Yellows for staking! In the works.
    fontawesome_icon_name                 : star



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#c7a008"
cover_overlay_transparency                : 0.8

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#ffcb05"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown